Update API for Grocery Lists
Grocee/grocee pull request #8
Opened 2018-04-29 21:15 UTC by indirap

2018-04-29 21:46 UTC, indirap commented
TODO
- [ ] Add tests

2018-05-02 00:21 UTC, vatthikorn approved these changes

2018-05-02 00:21 UTC, vatthikorn commented on imports/api/groceries.js
> +const authCheck = (groceryId) => {
This is neat. I probably should just pull this out to some sort of util class or somewhere that can be accessed for other APIs as well.

2018-05-02 01:06 UTC, indirap commented on imports/api/groceries.js
> +const authCheck = (groceryId) => {
Yeah! I can put it in a separate file so we can reuse it.

2018-05-02 02:40 UTC, vatthikorn requested changes

2018-05-02 02:40 UTC, zackva commented on utils/authorization.js
> +}
These references to grocery should probably be changed to something more generic

2018-05-23 23:42 UTC, vatthikorn approved these changes

2018-05-23 23:42 UTC, merged